export interface StateInfo {
  name: string;
  code: string;
  capital: string;
  region: 'North' | 'South' | 'East' | 'West' | 'Northeast' | 'Central' | 'UT';
  isUT: boolean;
  topExams: string[];
  topCollegeCategories: string[];
  popularCareers: string[];
  keyIndustries: string[];
  admissionGuidance: string;
  officialBoardWebsite?: string;
  boardName?: string;
}

export const STATES_DATA: StateInfo[] = [
  // North India
  {
    name: 'Delhi',
    code: 'DL',
    capital: 'New Delhi',
    region: 'UT',
    isUT: true,
    topExams: ['JEE Main', 'JEE Advanced', 'NEET', 'CUET', 'CLAT', 'CAT'],
    topCollegeCategories: ['Engineering', 'Medical', 'Law', 'MBA', 'Commerce', 'Arts'],
    popularCareers: ['Software Engineer', 'Civil Services', 'Doctor', 'Lawyer', 'CA'],
    keyIndustries: ['IT', 'Government', 'Finance', 'Media', 'Healthcare'],
    admissionGuidance: 'Delhi has some of India\'s most competitive colleges including IIT Delhi, AIIMS, NLUD, and DU. Most central universities use CUET for admissions. Engineering uses JEE Main/Advanced and Delhi state quota through JEE.',
    boardName: 'CBSE / Delhi Board',
  },
  {
    name: 'Uttar Pradesh',
    code: 'UP',
    capital: 'Lucknow',
    region: 'North',
    isUT: false,
    topExams: ['JEE Main', 'NEET', 'CUET', 'UPSEE', 'UPSC', 'UP PCS'],
    topCollegeCategories: ['Engineering', 'Medical', 'Arts', 'Commerce', 'Agriculture'],
    popularCareers: ['Engineer', 'Doctor', 'Civil Services', 'Teacher', 'Lawyer'],
    keyIndustries: ['Agriculture', 'IT', 'Manufacturing', 'Government', 'Education'],
    admissionGuidance: 'UP has IIT Kanpur, IIT BHU, MNNIT Allahabad, and KGMU. State engineering colleges admit through UPSEE. Medical via NEET. Many students target UPSC and UP PCS exams for government jobs.',
    officialBoardWebsite: 'https://upmsp.edu.in',
    boardName: 'UP Board (UPMSP)',
  },
  {
    name: 'Rajasthan',
    code: 'RJ',
    capital: 'Jaipur',
    region: 'North',
    isUT: false,
    topExams: ['JEE Main', 'JEE Advanced', 'NEET', 'BITSAT', 'Rajasthan CET'],
    topCollegeCategories: ['Engineering', 'Medical', 'MBA', 'Architecture', 'Arts'],
    popularCareers: ['Engineer', 'Doctor', 'Civil Services', 'CA', 'Hospitality'],
    keyIndustries: ['Tourism', 'Mining', 'Textiles', 'Agriculture', 'IT'],
    admissionGuidance: 'Home to BITS Pilani, IIT Jodhpur, and MNIT Jaipur. Rajasthan state engineering admissions through REAP. Medical via NEET. Strong government job culture with Rajasthan RPSC exams.',
    officialBoardWebsite: 'https://rajeduboard.rajasthan.gov.in',
    boardName: 'RBSE',
  },
  {
    name: 'Punjab',
    code: 'PB',
    capital: 'Chandigarh',
    region: 'North',
    isUT: false,
    topExams: ['JEE Main', 'NEET', 'CAT', 'HSTES', 'Punjab Police'],
    topCollegeCategories: ['Engineering', 'Medical', 'Agriculture', 'Pharmacy', 'MBA'],
    popularCareers: ['Engineer', 'Doctor', 'Farmer/Agribusiness', 'Armed Forces', 'CA'],
    keyIndustries: ['Agriculture', 'IT', 'Manufacturing', 'Food Processing', 'Defence'],
    admissionGuidance: 'Thapar Institute and PEC Chandigarh are top engineering colleges. Punjab Agricultural University is top for agriculture. NIT Jalandhar for engineering. HSTES manages state engineering admissions.',
    officialBoardWebsite: 'https://pseb.ac.in',
    boardName: 'PSEB',
  },
  {
    name: 'Haryana',
    code: 'HR',
    capital: 'Chandigarh',
    region: 'North',
    isUT: false,
    topExams: ['JEE Main', 'NEET', 'HSTES', 'HPSC', 'CAT'],
    topCollegeCategories: ['Engineering', 'Medical', 'Law', 'Agriculture', 'MBA'],
    popularCareers: ['Engineer', 'Lawyer', 'Civil Services', 'Doctor', 'Athlete'],
    keyIndustries: ['Auto Manufacturing', 'IT', 'Agriculture', 'Pharmaceuticals', 'Real Estate'],
    admissionGuidance: 'NIT Kurukshetra and Jindal Global Law School are premier institutes. Haryana state engineering via HSTES. Strong Gurugram IT job market. Many students target HPSC state civil services.',
    officialBoardWebsite: 'https://bseh.org.in',
    boardName: 'HBSE',
  },
  {
    name: 'Himachal Pradesh',
    code: 'HP',
    capital: 'Shimla',
    region: 'North',
    isUT: false,
    topExams: ['JEE Main', 'NEET', 'JEE Advanced', 'HPTET', 'HP CET'],
    topCollegeCategories: ['Engineering', 'Medical', 'Agriculture', 'Hospitality', 'Arts'],
    popularCareers: ['Engineer', 'Teacher', 'Doctor', 'Tourism/Hospitality', 'Civil Services'],
    keyIndustries: ['Horticulture', 'Tourism', 'Hydropower', 'Pharmaceuticals', 'IT'],
    admissionGuidance: 'IIT Mandi and NIT Hamirpur are the top engineering institutes. HP University in Shimla for arts and commerce. Strong pharmaceutical sector offers good pharmacy career prospects.',
    officialBoardWebsite: 'https://hpbose.org',
    boardName: 'HPBOSE',
  },
  {
    name: 'Uttarakhand',
    code: 'UK',
    capital: 'Dehradun',
    region: 'North',
    isUT: false,
    topExams: ['JEE Main', 'JEE Advanced', 'NEET', 'JEECUP', 'Uttarakhand PSC'],
    topCollegeCategories: ['Engineering', 'Medical', 'Pharmacy', 'Agriculture', 'MBA'],
    popularCareers: ['Engineer', 'Doctor', 'Pharmacist', 'Civil Services', 'Tourism'],
    keyIndustries: ['Pharmaceuticals', 'Tourism', 'FMCG', 'IT', 'Hydropower'],
    admissionGuidance: 'IIT Roorkee is India\'s oldest technical institute. NIT Uttarakhand for engineering. Graphic Era University is a notable private institute. JEECUP for polytechnic admissions.',
    officialBoardWebsite: 'https://ubse.uk.gov.in',
    boardName: 'UBSE',
  },
  {
    name: 'Jammu and Kashmir',
    code: 'JK',
    capital: 'Srinagar / Jammu',
    region: 'UT',
    isUT: true,
    topExams: ['JEE Main', 'NEET', 'JKSET', 'NIT J&K Entrance', 'JKPSC'],
    topCollegeCategories: ['Engineering', 'Medical', 'Arts', 'Agriculture', 'Law'],
    popularCareers: ['Engineer', 'Doctor', 'Civil Services', 'Teacher', 'Tourism'],
    keyIndustries: ['Tourism', 'Handicrafts', 'Agriculture', 'Horticulture', 'Government'],
    admissionGuidance: 'NIT Srinagar and IIT Jammu are top engineering institutes. SMVDU in Katra for engineering and management. JKBOSE board students get state quota in J&K institutions.',
    officialBoardWebsite: 'https://jkbose.nic.in',
    boardName: 'JKBOSE',
  },

  // South India
  {
    name: 'Karnataka',
    code: 'KA',
    capital: 'Bengaluru',
    region: 'South',
    isUT: false,
    topExams: ['JEE Main', 'JEE Advanced', 'NEET', 'KCET', 'COMEDK', 'CAT'],
    topCollegeCategories: ['Engineering', 'Medical', 'MBA', 'Law', 'Design', 'Architecture'],
    popularCareers: ['Software Engineer', 'Doctor', 'Business Analyst', 'Data Scientist', 'Designer'],
    keyIndustries: ['IT/Software', 'Aerospace', 'Biotech', 'Manufacturing', 'Textiles'],
    admissionGuidance: 'Bengaluru is India\'s tech capital. KCET and COMEDK are key state-level exams for engineering. IISc, IIT Dharwad, NIT Surathkal, and 200+ private engineering colleges. NLSIU for law.',
    officialBoardWebsite: 'https://kseab.karnataka.gov.in',
    boardName: 'KSEAB / PUC',
  },
  {
    name: 'Tamil Nadu',
    code: 'TN',
    capital: 'Chennai',
    region: 'South',
    isUT: false,
    topExams: ['JEE Main', 'NEET', 'TNEA', 'TANCET', 'CAT'],
    topCollegeCategories: ['Engineering', 'Medical', 'Arts', 'Law', 'Pharmacy', 'MBA'],
    popularCareers: ['Engineer', 'Doctor', 'Software Developer', 'CA', 'Civil Services'],
    keyIndustries: ['Auto Manufacturing', 'IT', 'Textiles', 'Agriculture', 'Healthcare'],
    admissionGuidance: 'TN uses TNEA for state engineering admissions (12th marks based). IIT Madras, NIT Trichy, VIT, SRM, and Anna University are top picks. NEET for medical. 12th marks are crucial for TNEA.',
    officialBoardWebsite: 'https://dge.tn.gov.in',
    boardName: 'Tamil Nadu State Board',
  },
  {
    name: 'Kerala',
    code: 'KL',
    capital: 'Thiruvananthapuram',
    region: 'South',
    isUT: false,
    topExams: ['JEE Main', 'NEET', 'KEAM', 'CUSAT CAT', 'KPSC'],
    topCollegeCategories: ['Engineering', 'Medical', 'Nursing', 'Arts', 'Law', 'MBA'],
    popularCareers: ['Engineer', 'Doctor', 'Nurse', 'Civil Services', 'Software Developer'],
    keyIndustries: ['IT', 'Tourism', 'Healthcare', 'Banking', 'Remittances/Gulf Jobs'],
    admissionGuidance: 'KEAM is the key state exam for engineering and pharmacy. IIT Palakkad, NIT Calicut, and CUSAT are top institutes. Kerala has high literacy and strong demand for medical and nursing careers. Many seek Gulf employment.',
    officialBoardWebsite: 'https://keralapareekshabhavan.in',
    boardName: 'Kerala DHSE',
  },
  {
    name: 'Andhra Pradesh',
    code: 'AP',
    capital: 'Amaravati',
    region: 'South',
    isUT: false,
    topExams: ['JEE Main', 'NEET', 'AP EAPCET', 'AP ICET', 'AP PGECET'],
    topCollegeCategories: ['Engineering', 'Medical', 'Pharmacy', 'Agriculture', 'MBA'],
    popularCareers: ['Software Engineer', 'Doctor', 'Civil Services', 'Pharmacist', 'Agriculturist'],
    keyIndustries: ['IT', 'Pharma', 'Agriculture', 'Aquaculture', 'Cement/Mining'],
    admissionGuidance: 'AP EAPCET (formerly EAMCET) is the main state exam for engineering, pharmacy, and agriculture. IIT Tirupati, NIT Andhra Pradesh, Andhra University are top choices. Strong Hyderabad IT proximity benefits AP students.',
    officialBoardWebsite: 'https://bse.ap.gov.in',
    boardName: 'BSEAP',
  },
  {
    name: 'Telangana',
    code: 'TS',
    capital: 'Hyderabad',
    region: 'South',
    isUT: false,
    topExams: ['JEE Main', 'JEE Advanced', 'NEET', 'TS EAMCET', 'TS ICET', 'CAT'],
    topCollegeCategories: ['Engineering', 'Medical', 'MBA', 'Law', 'Pharmacy', 'Design'],
    popularCareers: ['Software Engineer', 'Data Scientist', 'Doctor', 'Business Analyst', 'Civil Services'],
    keyIndustries: ['IT/Software', 'Pharma', 'Manufacturing', 'Finance', 'Biotech'],
    admissionGuidance: 'Hyderabad is a major tech hub. TS EAMCET for state engineering/medical. IIT Hyderabad, IIIT Hyderabad, NALSAR, ISB, and BITS Hyderabad are top choices. Strong private engineering college ecosystem.',
    officialBoardWebsite: 'https://bse.telangana.gov.in',
    boardName: 'BSETS',
  },

  // West India
  {
    name: 'Maharashtra',
    code: 'MH',
    capital: 'Mumbai',
    region: 'West',
    isUT: false,
    topExams: ['JEE Main', 'NEET', 'MHT CET', 'CAT', 'CLAT', 'CMAT'],
    topCollegeCategories: ['Engineering', 'Medical', 'MBA', 'Law', 'Design', 'Architecture'],
    popularCareers: ['Software Engineer', 'Finance Professional', 'Doctor', 'Lawyer', 'Film/Media'],
    keyIndustries: ['Finance', 'IT', 'Manufacturing', 'Entertainment', 'Pharma'],
    admissionGuidance: 'MHT CET is the main state exam for engineering and pharmacy. IIT Bombay, COEP, VJTI, AFMC are top picks. Mumbai offers vast opportunities in finance, IT, and media. Mumbai University for arts and commerce.',
    officialBoardWebsite: 'https://mahahsscboard.in',
    boardName: 'Maharashtra State Board (MSBSHSE)',
  },
  {
    name: 'Gujarat',
    code: 'GJ',
    capital: 'Gandhinagar',
    region: 'West',
    isUT: false,
    topExams: ['JEE Main', 'JEE Advanced', 'NEET', 'GUJCET', 'CAT'],
    topCollegeCategories: ['Engineering', 'Medical', 'MBA', 'Pharmacy', 'Commerce', 'Design'],
    popularCareers: ['Engineer', 'Doctor', 'Entrepreneur', 'CA', 'Business Manager'],
    keyIndustries: ['Manufacturing', 'Chemicals/Pharma', 'Diamonds', 'Textiles', 'Ports/Trade'],
    admissionGuidance: 'GUJCET for state engineering and pharmacy admissions. IIT Gandhinagar, NID Ahmedabad, NIT Surat, IIM Ahmedabad, and CEPT are top choices. Gujarat has a strong entrepreneurial culture.',
    officialBoardWebsite: 'https://gseb.org',
    boardName: 'GSEB',
  },
  {
    name: 'Goa',
    code: 'GA',
    capital: 'Panaji',
    region: 'West',
    isUT: false,
    topExams: ['JEE Main', 'NEET', 'Goa CET', 'CAT'],
    topCollegeCategories: ['Engineering', 'Medical', 'Arts', 'Hospitality', 'Commerce'],
    popularCareers: ['Hospitality Manager', 'Engineer', 'Doctor', 'Tourism Professional', 'Artist'],
    keyIndustries: ['Tourism', 'Mining', 'Fishing', 'IT', 'Hospitality'],
    admissionGuidance: 'IIT Goa and NIT Goa are top engineering options. Goa University for arts and commerce. State CET for local engineering colleges. Strong tourism industry creates hospitality and travel careers.',
    officialBoardWebsite: 'https://gbshse.gov.in',
    boardName: 'Goa Board (GBSHSE)',
  },

  // East India
  {
    name: 'West Bengal',
    code: 'WB',
    capital: 'Kolkata',
    region: 'East',
    isUT: false,
    topExams: ['JEE Main', 'JEE Advanced', 'NEET', 'WBJEE', 'WBPSC', 'CAT'],
    topCollegeCategories: ['Engineering', 'Medical', 'Arts', 'Law', 'Commerce', 'MBA'],
    popularCareers: ['Engineer', 'Doctor', 'Civil Services', 'Scientist', 'Artist/Creative'],
    keyIndustries: ['IT', 'Manufacturing', 'Jute', 'Tea', 'Finance'],
    admissionGuidance: 'WBJEE is the state engineering entrance exam. Jadavpur University and IIT Kharagpur are the most prestigious. NUJS for law, IIM Calcutta for MBA. Kolkata is a cultural and academic hub.',
    officialBoardWebsite: 'https://wbchse.wb.gov.in',
    boardName: 'WBCHSE',
  },
  {
    name: 'Odisha',
    code: 'OD',
    capital: 'Bhubaneswar',
    region: 'East',
    isUT: false,
    topExams: ['JEE Main', 'NEET', 'OJEE', 'OPSC', 'CAT'],
    topCollegeCategories: ['Engineering', 'Medical', 'Agriculture', 'Arts', 'Commerce'],
    popularCareers: ['Engineer', 'Doctor', 'Civil Services', 'IT Professional', 'Miner/Metallurgist'],
    keyIndustries: ['Mining/Steel', 'IT', 'Agriculture', 'Fisheries', 'Tourism'],
    admissionGuidance: 'OJEE for state-level lateral entry and some engineering admissions. IIT Bhubaneswar, NIT Rourkela, IIIT Bhubaneswar are top choices. Strong mining industry drives demand for metallurgy and mining engineering.',
    officialBoardWebsite: 'https://bseodisha.ac.in',
    boardName: 'BSE Odisha',
  },
  {
    name: 'Bihar',
    code: 'BR',
    capital: 'Patna',
    region: 'East',
    isUT: false,
    topExams: ['JEE Main', 'NEET', 'BCECE', 'BPSC', 'CAT'],
    topCollegeCategories: ['Engineering', 'Medical', 'Arts', 'Agriculture', 'Law'],
    popularCareers: ['Civil Services (UPSC/BPSC)', 'Doctor', 'Teacher', 'Engineer', 'Lawyer'],
    keyIndustries: ['Agriculture', 'Government', 'Education', 'Construction', 'Food Processing'],
    admissionGuidance: 'IIT Patna and NIT Patna are top engineering institutes. BCECE for state medical and engineering. Bihar has a strong civil services culture — UPSC and BPSC are highly competitive goals. Chandragupt IMB for management.',
    officialBoardWebsite: 'https://biharboardonline.bihar.gov.in',
    boardName: 'BSEB',
  },
  {
    name: 'Jharkhand',
    code: 'JH',
    capital: 'Ranchi',
    region: 'East',
    isUT: false,
    topExams: ['JEE Main', 'JEE Advanced', 'NEET', 'JCECE', 'JPSC'],
    topCollegeCategories: ['Engineering', 'Medical', 'Agriculture', 'MBA', 'Mining'],
    popularCareers: ['Mining Engineer', 'Civil Services', 'Doctor', 'IT Professional', 'Forest Officer'],
    keyIndustries: ['Mining/Steel', 'Forestry', 'Agriculture', 'Manufacturing', 'Power'],
    admissionGuidance: 'IIT (ISM) Dhanbad is a top choice for mining and metallurgy. XLRI Jamshedpur for management. NIT Jamshedpur for engineering. JCECE for state-level engineering and medical admissions.',
    officialBoardWebsite: 'https://jac.jharkhand.gov.in',
    boardName: 'JAC',
  },

  // Central India
  {
    name: 'Madhya Pradesh',
    code: 'MP',
    capital: 'Bhopal',
    region: 'Central',
    isUT: false,
    topExams: ['JEE Main', 'JEE Advanced', 'NEET', 'MP PET', 'MPPSC', 'CAT'],
    topCollegeCategories: ['Engineering', 'Medical', 'Agriculture', 'Arts', 'MBA', 'Architecture'],
    popularCareers: ['Engineer', 'Doctor', 'Civil Services', 'Teacher', 'Agriculturist'],
    keyIndustries: ['Agriculture', 'Mining', 'Manufacturing', 'Tourism', 'IT'],
    admissionGuidance: 'IIT Indore, MANIT Bhopal, and SPA Bhopal are top choices. MP PET for state engineering. IIM Indore for MBA. MP has a strong tradition of civil services aspirants targeting MPPSC and UPSC.',
    officialBoardWebsite: 'https://mpbse.nic.in',
    boardName: 'MPBSE',
  },
  {
    name: 'Chhattisgarh',
    code: 'CG',
    capital: 'Raipur',
    region: 'Central',
    isUT: false,
    topExams: ['JEE Main', 'NEET', 'CG PET', 'CGPSC'],
    topCollegeCategories: ['Engineering', 'Medical', 'Agriculture', 'Mining', 'Arts'],
    popularCareers: ['Mining Engineer', 'Doctor', 'Civil Services', 'Teacher', 'Steel Industry'],
    keyIndustries: ['Mining/Steel', 'Power', 'Agriculture', 'Cement', 'Forestry'],
    admissionGuidance: 'IIT Bhilai and NIT Raipur are top engineering options. CG PET for state engineering. IIM Raipur for management. Mining and steel industries offer strong career prospects locally.',
    officialBoardWebsite: 'https://cgbse.nic.in',
    boardName: 'CGBSE',
  },

  // Northeast India
  {
    name: 'Assam',
    code: 'AS',
    capital: 'Dispur',
    region: 'Northeast',
    isUT: false,
    topExams: ['JEE Main', 'NEET', 'ASSAM CEE', 'APSC', 'CAT'],
    topCollegeCategories: ['Engineering', 'Medical', 'Agriculture', 'Arts', 'Commerce'],
    popularCareers: ['Engineer', 'Doctor', 'Civil Services', 'Tea Industry Professional', 'Forest Officer'],
    keyIndustries: ['Tea', 'Petroleum', 'Agriculture', 'Tourism', 'Handloom'],
    admissionGuidance: 'IIT Guwahati is the top engineering institute. NIT Silchar and Gauhati University are other key options. ASSAM CEE for state engineering. APSC for state civil services. Petroleum sector offers good career scope.',
    officialBoardWebsite: 'https://sebaonline.org',
    boardName: 'SEBA / AHSEC',
  },
  {
    name: 'Manipur',
    code: 'MN',
    capital: 'Imphal',
    region: 'Northeast',
    isUT: false,
    topExams: ['JEE Main', 'NEET', 'Manipur CET', 'MPSC'],
    topCollegeCategories: ['Engineering', 'Medical', 'Arts', 'Agriculture', 'Sports'],
    popularCareers: ['Civil Services', 'Sports Professional', 'Doctor', 'Engineer', 'Teacher'],
    keyIndustries: ['Agriculture', 'Handloom', 'Handicrafts', 'Tourism', 'Government'],
    admissionGuidance: 'NIT Manipur is the top engineering option. Manipur University for arts and sciences. Strong sports culture — National Sports University is in Manipur. MPSC for state civil services.',
    officialBoardWebsite: 'https://manibose.nic.in',
    boardName: 'BSEM / COHSEM',
  },
  {
    name: 'Meghalaya',
    code: 'ML',
    capital: 'Shillong',
    region: 'Northeast',
    isUT: false,
    topExams: ['JEE Main', 'NEET', 'Meghalaya CET', 'MPSC'],
    topCollegeCategories: ['Engineering', 'Medical', 'Arts', 'Commerce', 'Hospitality'],
    popularCareers: ['Civil Services', 'Teacher', 'Engineer', 'Doctor', 'Tourism'],
    keyIndustries: ['Mining', 'Tourism', 'Agriculture', 'Cement', 'Government'],
    admissionGuidance: 'IIM Shillong and NIT Meghalaya are the top national institutes. North-Eastern Hill University for arts and sciences. Tourism sector offers growing career opportunities.',
    officialBoardWebsite: 'https://mbose.in',
    boardName: 'MBOSE',
  },
  {
    name: 'Mizoram',
    code: 'MZ',
    capital: 'Aizawl',
    region: 'Northeast',
    isUT: false,
    topExams: ['JEE Main', 'NEET', 'Mizoram CET', 'MPSC'],
    topCollegeCategories: ['Engineering', 'Medical', 'Arts', 'Nursing', 'Commerce'],
    popularCareers: ['Civil Services', 'Doctor', 'Nurse', 'Teacher', 'Engineer'],
    keyIndustries: ['Agriculture', 'Bamboo/Timber', 'Handloom', 'Tourism', 'Government'],
    admissionGuidance: 'NIT Mizoram for engineering. Mizoram University for arts and sciences. Nursing is a highly popular career due to employment opportunities in metros and abroad.',
    officialBoardWebsite: 'https://mbse.edu.in',
    boardName: 'MBSE',
  },
  {
    name: 'Nagaland',
    code: 'NL',
    capital: 'Kohima',
    region: 'Northeast',
    isUT: false,
    topExams: ['JEE Main', 'NEET', 'Nagaland CET', 'NPSC'],
    topCollegeCategories: ['Engineering', 'Medical', 'Arts', 'Commerce', 'Agriculture'],
    popularCareers: ['Civil Services', 'Teacher', 'Doctor', 'Engineer', 'Tourism'],
    keyIndustries: ['Agriculture', 'Tourism', 'Handicrafts', 'Forest Products', 'Government'],
    admissionGuidance: 'NIT Nagaland for engineering. Nagaland University for arts and sciences. NPSC for state civil services. Agriculture and tourism are growing career sectors.',
    officialBoardWebsite: 'https://nbsenagaland.com',
    boardName: 'NBSE',
  },
  {
    name: 'Arunachal Pradesh',
    code: 'AR',
    capital: 'Itanagar',
    region: 'Northeast',
    isUT: false,
    topExams: ['JEE Main', 'NEET', 'APPSC', 'Arunachal CET'],
    topCollegeCategories: ['Engineering', 'Medical', 'Arts', 'Agriculture', 'Nursing'],
    popularCareers: ['Civil Services', 'Teacher', 'Doctor', 'Forest Officer', 'Engineer'],
    keyIndustries: ['Hydropower', 'Tourism', 'Agriculture', 'Timber', 'Government'],
    admissionGuidance: 'NIT Arunachal Pradesh for engineering. Rajiv Gandhi University for higher education. Hydropower sector offers good engineering career opportunities. APPSC for state civil services.',
    officialBoardWebsite: 'https://dhte.arunachal.gov.in',
    boardName: 'CBSE affiliated / DHTE',
  },
  {
    name: 'Tripura',
    code: 'TR',
    capital: 'Agartala',
    region: 'Northeast',
    isUT: false,
    topExams: ['JEE Main', 'NEET', 'TBJEE', 'TPSC'],
    topCollegeCategories: ['Engineering', 'Medical', 'Arts', 'Commerce', 'Agriculture'],
    popularCareers: ['Civil Services', 'IT Professional', 'Doctor', 'Teacher', 'Engineer'],
    keyIndustries: ['Natural Gas', 'Agriculture', 'Bamboo/Wood', 'IT', 'Government'],
    admissionGuidance: 'NIT Agartala is the top engineering college. TBJEE for state engineering and medical. Tripura University for arts and commerce. Natural gas industry offers energy sector career opportunities.',
    officialBoardWebsite: 'https://tbse.tripura.gov.in',
    boardName: 'TBSE',
  },
  {
    name: 'Sikkim',
    code: 'SK',
    capital: 'Gangtok',
    region: 'Northeast',
    isUT: false,
    topExams: ['JEE Main', 'NEET', 'Sikkim CET', 'SPSC'],
    topCollegeCategories: ['Engineering', 'Medical', 'Hospitality', 'Commerce', 'Agriculture'],
    popularCareers: ['Tourism/Hospitality', 'Civil Services', 'Doctor', 'Engineer', 'Teacher'],
    keyIndustries: ['Tourism', 'Hydropower', 'Agriculture', 'Cardamom/Spices', 'Government'],
    admissionGuidance: 'NIT Sikkim for engineering. Sikkim University for arts and sciences. Tourism is a booming industry — hotel management and travel careers have strong demand. SPSC for state civil services.',
    boardName: 'CBSE affiliated',
  },

  // Union Territories
  {
    name: 'Chandigarh',
    code: 'CH',
    capital: 'Chandigarh',
    region: 'UT',
    isUT: true,
    topExams: ['JEE Main', 'NEET', 'CAT', 'CUET', 'HSTES'],
    topCollegeCategories: ['Engineering', 'Medical', 'Law', 'Commerce', 'Arts'],
    popularCareers: ['Engineer', 'Doctor', 'Civil Services', 'Lawyer', 'CA'],
    keyIndustries: ['IT', 'Government', 'Education', 'Healthcare', 'Real Estate'],
    admissionGuidance: 'PEC (Punjab Engineering College) and PGIMER are top institutions. Chandigarh University is a notable private option. Being Punjab\'s and Haryana\'s capital gives access to strong job markets.',
    boardName: 'CBSE affiliated',
  },
  {
    name: 'Puducherry',
    code: 'PY',
    capital: 'Puducherry',
    region: 'UT',
    isUT: true,
    topExams: ['JEE Main', 'NEET', 'Pondicherry CET', 'UPSC'],
    topCollegeCategories: ['Engineering', 'Medical', 'Arts', 'Law', 'Commerce'],
    popularCareers: ['Doctor', 'Engineer', 'Civil Services', 'Tourism', 'Teacher'],
    keyIndustries: ['Tourism', 'Pharmaceuticals', 'IT', 'Fishing', 'Government'],
    admissionGuidance: 'JIPMER Pondicherry is India\'s top medical institute. Pondicherry University offers engineering and arts programs. French colonial heritage makes it a unique destination for arts and tourism careers.',
    boardName: 'Tamil Nadu / CBSE Board',
  },
  {
    name: 'Ladakh',
    code: 'LA',
    capital: 'Leh',
    region: 'UT',
    isUT: true,
    topExams: ['JEE Main', 'NEET', 'LADHPSC'],
    topCollegeCategories: ['Arts', 'Commerce', 'Engineering', 'Tourism', 'Agriculture'],
    popularCareers: ['Tourism Professional', 'Civil Services', 'Teacher', 'Army Officer', 'Engineer'],
    keyIndustries: ['Tourism', 'Renewable Energy', 'Government/Defence', 'Agriculture', 'Handicrafts'],
    admissionGuidance: 'Ladakh University is a central university. Students often move to Jammu or Delhi for professional courses. Tourism and renewable energy (solar/hydro) offer growing local career prospects.',
    boardName: 'JKBOSE / CBSE',
  },
  {
    name: 'Andaman and Nicobar Islands',
    code: 'AN',
    capital: 'Port Blair',
    region: 'UT',
    isUT: true,
    topExams: ['JEE Main', 'NEET', 'CUET', 'UPSC'],
    topCollegeCategories: ['Arts', 'Commerce', 'Marine Science', 'Tourism', 'Engineering'],
    popularCareers: ['Marine Biologist', 'Tourism Professional', 'Civil Services', 'Fisheries Officer', 'Teacher'],
    keyIndustries: ['Tourism', 'Fishing', 'Government', 'Marine Sciences', 'Defence'],
    admissionGuidance: 'Dr. B.R. Ambedkar Institute of Technology for engineering. Students usually move to mainland for competitive colleges. Marine science and fisheries offer unique career paths here.',
    boardName: 'CBSE affiliated',
  },
  {
    name: 'Lakshadweep',
    code: 'LD',
    capital: 'Kavaratti',
    region: 'UT',
    isUT: true,
    topExams: ['JEE Main', 'NEET', 'CUET'],
    topCollegeCategories: ['Arts', 'Commerce', 'Marine Science', 'Tourism'],
    popularCareers: ['Marine Scientist', 'Fisheries Officer', 'Tourism Professional', 'Civil Services', 'Teacher'],
    keyIndustries: ['Fishing', 'Tourism', 'Coconut Products', 'Government', 'Marine Sciences'],
    admissionGuidance: 'Students typically relocate to Kerala for higher education. Limited local college options. Marine science, fisheries, and tourism are natural career choices given the island geography.',
    boardName: 'CBSE affiliated',
  },
  {
    name: 'Dadra and Nagar Haveli and Daman and Diu',
    code: 'DH',
    capital: 'Daman',
    region: 'UT',
    isUT: true,
    topExams: ['JEE Main', 'NEET', 'GUJCET', 'CAT'],
    topCollegeCategories: ['Engineering', 'Medical', 'Commerce', 'Arts', 'Pharmacy'],
    popularCareers: ['Engineer', 'Doctor', 'Businessman', 'Tourism Professional', 'Industrial Worker'],
    keyIndustries: ['Manufacturing', 'Tourism', 'Fishing', 'Trade', 'Chemicals'],
    admissionGuidance: 'Students typically use Gujarat or Maharashtra boards and exams. Proximity to Surat and Mumbai gives access to major job markets. Manufacturing sector in Silvassa offers engineering career opportunities.',
    boardName: 'Gujarat Board / CBSE',
  },
];
